name: Create release

on:
  push:
    tags:
    - '*'

jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install tools
        run: |
          sudo apt-get install python3 python3-pip
          pip3 install wheel

      - name: Build package
        run: python3 setup.py sdist bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  create-github-release:
    needs: build-package
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Create github release
        uses: "softprops/action-gh-release@v1"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          prerelease: false
          files: dist/MacToManufacturer-*

  create-pypi-release:
    needs: build-package
    name: Create pypi release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Install tools
        run: |
          sudo apt-get install python3 python3-pip
          python3 -m pip install --upgrade twine

      - name: Release on pypi
        run: |
          python3 -m twine upload --username __token__ --password ${{ secrets.PYPI_SECRET }} --repository pypi dist/*