name: Create CSV

on:
  workflow_dispatch

jobs:
  create_csv:
    name: Create CSV file
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create csv file
        run: cd src/CreateCSV && python3 main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: manuf.csv
          path: src/manuf.csv
